export const SkillsData = [
  { name: "html", image: "html" },
  { name: "css", image: "css" },
  { name: "javascript", image: "javascript" },
  { name: "react js", image: "react" },
  { name: "next js", image: "next" },
  { name: "node js", image: "node" },
  { name: "express js", image: "express" },
  { name: "TYPESCRIPT ", image: "typescript" },
  { name: "tailwind css", image: "tailwind" },
  { name: "wordpress", image: "wordpress" },
  { name: ".Net core", image: "dotnetcore" },
  { name: "figma", image: "figma" },
  //   { name: "Adobe Illustrator", image: "illustrator" },
  { name: "Bootstrap", image: "bootstrap" },
  { name: "Mongo db", image: "mongodb" },
  { name: "my sql", image: "mysql" },
];
